language: go
services:
- docker
branches:
  except:
  - feature/*
env:
  global:
  - SERVER_IP_ADDRESS=207.246.89.240
  - SERVER_USERNAME=root
  - DOCKER_IMAGE=karthikraveendranoss/etsello:dev
  - DEPLOY_DIR=/root/etsello-develop
before_install:
- openssl aes-256-cbc -K $encrypted_48434d1b1ed5_key -iv $encrypted_48434d1b1ed5_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $SERVER_USERNAME@$SERVER_IP_ADDRESS pwd
- docker build --no-cache -t $DOCKER_IMAGE .
- docker-compose up -d
- docker ps
script:
- curl 127.0.0.1:8000
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker images
- docker push $DOCKER_IMAGE
after_success:
- ssh -i ./deploy_key $SERVER_USERNAME@$SERVER_IP_ADDRESS mkdir -p $DEPLOY_DIR
- scp -i ./deploy_key docker-compose.yaml etsello-deploy.sh $SERVER_USERNAME@$SERVER_IP_ADDRESS:$DEPLOY_DIR
- ssh -i ./deploy_key $SERVER_USERNAME@$SERVER_IP_ADDRESS chmod +x $DEPLOY_DIR/etsello-deploy.sh
- ssh -i ./deploy_key $SERVER_USERNAME@$SERVER_IP_ADDRESS $DEPLOY_DIR/etsello-deploy.sh $DOCKER_IMAGE $DEPLOY_DIR $ETSY_CONSUMER_KEY $ETSY_CONSUMER_SECRET $TRELLO_CONSUMER_KEY $TRELLO_CONSUMER_SECRET $HOST_URL $GTASKS_CLIENT_ID $GTASKS_CLIENT_SECRET
